name: "classifier_onnx"
platform: "onnxruntime_onnx"
max_batch_size: 32
input [
  {
    name: "input__0"
    data_type: TYPE_INT64
    dims: [ 1, 64 ]
  }
]
output {
  name: "output__0"
  data_type: TYPE_FP32
  dims: [ 1 ]
}
dynamic_batching {
  preferred_batch_size: [2, 4, 8, 16, 32]
  max_queue_delay_microseconds: 30000
}
instance_group [
    {
        count: 2
        kind: KIND_CPU
    }
]
